---

num_clients: 18 # total number of clients
num_epochs: 2 # number of local epochs
batch_size: 32
num_rounds: 10
clients_per_round: 4
stragglers_fraction: 0.9
learning_rate: 0.03
# model moon config

output_dim: 256
mu: 0.001
temperature: 0.5

client_resources:
  num_cpus: 2
  num_gpus: 1.0

server_device: cuda

dataset_config:
  iid: false
  balance: false
  power_law: true
  dataset_name: breastmnist

